### ISSUE TITLE
Setup.py/submission to pypi?

### ISSUE THREAD

**Issue by Ciemaar** [handyman5/poodledo#6]
Wou/d a patch to add a setup.py file and add poodledo to the python package index be ok?  I want to eventually add a package I'm working on and list it as a dependency or an optional dependency, not sure yet.

**Comment by handyman5** [comment]
Yeah, I noticed that @dsmcfarl [has done that as well](https://github.com/dsmcfarl/poodledo). The reasons I haven't done it myself are:
- I don't know how `pip install` interacts with multiple tools, like if I should make "poodledo" install tdcli and cycle as well or have separate packages for them that depend on poodledo
- Since I don't provide an API key, I'm concerned people will install poodledo without reading the docs and then come bitch to me that it doesn't work out of the box.

I'm not at all opposed to the idea, though, so if you want to code it up and submit a pull request I'd be happy to see it.

Thanks,
Adam

**Comment by dsmcfarl** [comment]
I'm a novice at packaging, but you should be able to add a "scripts" parameter to the setup function in setup.py to install tdcli and cycle to the bin or scripts directory during install. I didn't add this because all I'm using is the API client, and just wanted to be able to add the repo to a pip requirements.txt file for a project I'm working on.

**Comment by handyman5** [comment]
Duly noted, thanks!

**Comment by iandennismiller** [comment]
Sorry, I didn't notice this thread before I submitted a pull request: 

https://github.com/handyman5/poodledo/pull/7

I am also not an expert at packaging, but setup.py will install the scripts to a runnable location.  There is more work to be done in order for testing to be integrated with the Makefile, and setup.py needs some author-related metadata, but I believe it's 90% ready for redistribution.

**Comment by handyman5** [comment]
I've incorporated @iandennismiller's changes into the master branch and uploaded the project to pypi, so I consider this issue closed. Thanks for your help and support, guys! It's great to know people are using this tool.
